### ISSUE TITLE
ErlEF Stipend

### ISSUE THREAD

**Issue by maennchen** [erlef/oidcc#221]
## Work Packages

- [x] Setup CI - oidcc
- [x] Cleanup and Refactor current modules
  - [x] Error Types
  - [x] Elixir Bindings
  - [x] JSON Web Token (JWT) Profile for OAuth 2.0 Client
- [x] Replace erljwt with jose
- [x] Implement telemetry instrumentation
  - [x] Metadata / Jwk
  - [x] Token Request
  - [x] Userinfo Request
  - [x] Introspection
- [x] Write Documentation
  - [x] Document Telemetry Events
- [x] Implement Cowboy Integration - https://github.com/Erlang-Openid/oidcc_cowboy/issues/22
- [x] Implement Plug Integration - https://github.com/Erlang-Openid/oidcc_plug/issues/1
- [x] Implement phx_gen_oidcc - https://github.com/Erlang-Openid/phx_gen_oidcc/issues/1
- [x] Certify Library - #233
- [ ] Conference Talk
  - [X] [Submission](https://sessionize.com/s/maennchen/unlock-the-power-of-openid-connect-on-the-beam/77511) for [Code Beam America](https://codebeamamerica.com/)
  - [ ] Write talk
  - [ ] Do it

## TODOs
* [x] Move repos to @erlef - @peerst
* [x] Re-Enable coveralls.io - @peerst 
* [x] Improve PKCE ergonomics
* [x] Public Testing
* [x] Add security policy to all libs - https://github.com/erlef/oidcc/pull/254
* [x] Stable Release

**Comment by maennchen** [comment]
Conference talk progress will be tracked outside GitHub. Closing issue.
